In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
a=np.array([[1,2,3,4],[5,6,7,8],[8,1,6,3]])
print(a[0],a[1])



[1 2 3 4] [5 6 7 8]


In [37]:
np.zeros(2)

array([0., 0.])

In [38]:
np.ones(2)

array([1., 1.])

In [39]:
np.empty(3)# Create an empty array with 2 elements

array([0. , 0.5, 1. ])

In [40]:
np.zeros((4,4)) #creates 4by4 matrix


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.arange(1,5,1) # create array withnp.arrange(first number,lastNumber,stepsize)   
                     #step size means distance wich is 1 

array([1, 2, 3, 4])

In [42]:
np.linspace(1,2,7) # create an array with values that are spaced linearly(fist,last,specified)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [43]:
np.random.random((1,5))#returns a random float number between 0 and 1

array([[0.36788598, 0.12966482, 0.06723463, 0.33526765, 0.9267831 ]])

In [44]:
print(f"array a:{a.dtype}")# datatype of array

array a:int32


In [45]:
print(f"ndim: {a.ndim}") # ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndim: 2


In [46]:
print(f"size: {a.size}") # 3rows 4columns(3,4) / multiplication 12

size: 12


In [47]:
print(f"shape: {a.shape}") # (rows,columns)=(3,4)

shape: (3, 4)


In [48]:
print(f"datatype: {a.dtype}")

datatype: int32


In [49]:
print(f"itemsize: {a.itemsize}") # individual size

itemsize: 4


In [50]:
data = np.array([1, 2, 3])

In [51]:
data[1]

2

In [52]:
data[0:2]

array([1, 2])

In [53]:
data[1:]

array([2, 3])

In [54]:
data[-2:]

array([2, 3])

In [58]:
b=np.array([[1,2,3,4],[4,5,6,7],[11,12,5,6]])

In [59]:
np.add(a,b) 

array([[ 2,  4,  6,  8],
       [ 9, 11, 13, 15],
       [19, 13, 11,  9]])

In [62]:
np.subtract(a,b)

array([[  0,   0,   0,   0],
       [  1,   1,   1,   1],
       [ -3, -11,   1,  -3]])

In [63]:
np.divide(a,b)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.25      , 1.2       , 1.16666667, 1.14285714],
       [0.72727273, 0.08333333, 1.2       , 0.5       ]])

In [64]:
np.mod(a,b)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [8, 1, 1, 3]])

In [65]:
np.multiply(a,b)

array([[ 1,  4,  9, 16],
       [20, 30, 42, 56],
       [88, 12, 30, 18]])

In [67]:
np.power(a,b)

array([[      1,       4,      27,     256],
       [    625,    7776,  117649, 2097152],
       [      0,       1,    7776,     729]])

In [68]:
np.abs(a,b) #absolute value

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 1, 6, 3]])

In [69]:
np.remainder(a,b)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
s=np.array(["vaishu","vishva","krishi","khushi"])
print(s)
print(f"size:{a.size}")
print(f"shape:{a.shape}")
print(f"dtype:{a.dtype}")
print(f"itemsize:{a.itemsize}")

['vaishu' 'vishva' 'krishi' 'khushi']
size:12
shape:(3, 4)
dtype:int32
itemsize:4


In [71]:
np.vstack((a, b)) #stack them vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 1, 6, 3],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 1, 6, 3]])

In [72]:
np.hstack((a,b))# stack horizontally

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8],
       [8, 1, 6, 3, 8, 1, 6, 3]])

In [77]:
x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [78]:
np.hsplit(x,3) # can split above array in 3 equal array

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [79]:
np.hsplit(x,(3,4))#split your array after the third and fourth column

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [80]:
a.max()

8

In [81]:
a.min()

1

In [82]:
a.sum()

54

In [83]:
print("initial array",a)

initial array [[1 2 3 4]
 [5 6 7 8]
 [8 1 6 3]]


In [85]:
sliced=a[:1:,1:]
print("sliced",sliced)

sliced [[2 3 4]]


In [86]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
indexed=a[[0,1],[1,1]]
print("indexed",indexed)

indexed [2 6]


In [88]:
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [8 1 6 3]]


In [89]:
print("sum",a.sum())

sum 54


In [90]:
print("sqrt",np.sqrt(a))

sqrt [[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [2.82842712 1.         2.44948974 1.73205081]]


In [92]:
print("add element in array",a+10)


add element in array [[11 12 13 14]
 [15 16 17 18]
 [18 11 16 13]]


In [93]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[4,5,6],[1,2,3],[7,8,9]])

matrix3=np.dot(matrix1,matrix2)

In [94]:
print(matrix3)

[[ 27  33  39]
 [ 63  78  93]
 [ 99 123 147]]


In [95]:
print("matrix pumtiplication",matrix3)#matrix multiplication

matrix pumtiplication [[ 27  33  39]
 [ 63  78  93]
 [ 99 123 147]]


In [96]:
print("transpose",format(matrix1.T))#if matrix(rows,columns)(3,4)the its transpose is (4,3)
                                    

transpose [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [97]:
print("mathamatical functions")
ar=np.array([1,2,3])
print("sqrt",np.sqrt(ar))
print("exp",np.exp(ar))
print("sin",np.sin(ar))
print("cos",np.cos(ar))
print("log",np.log(ar))
print("sum",np.sum(ar))
print("std",np.std(ar))
print("\n")

mathamatical functions
sqrt [1.         1.41421356 1.73205081]
exp [ 2.71828183  7.3890561  20.08553692]
sin [0.84147098 0.90929743 0.14112001]
cos [ 0.54030231 -0.41614684 -0.9899925 ]
log [0.         0.69314718 1.09861229]
sum 6
std 0.816496580927726




In [98]:
print("random",np.random.random(20))

random [0.54228253 0.39354443 0.94126824 0.38473899 0.4735798  0.96049817
 0.44108355 0.38990638 0.16536884 0.81040723 0.64052157 0.273266
 0.80036327 0.77936355 0.58191155 0.07871643 0.31579503 0.40474414
 0.96274532 0.81680815]


In [99]:
print("rand",np.random.rand(3,4))

rand [[0.3794098  0.66446599 0.45167393 0.71540223]
 [0.84261551 0.01888454 0.92763188 0.98894393]
 [0.51448216 0.95378954 0.14516309 0.01608251]]


In [100]:
print("randint",np.random.randint(0,100,20))

randint [81 70 93 62 74 83  0 47 94 80 91 81 75 92 58 14 67 18  0 83]


In [101]:
print("permutation",np.random.permutation(np.arange(20)))

permutation [ 0  9 14 19 15  5 12 10 16  6  7  8 17 11 13 18  2  4  1  3]


In [102]:
reversed_arr = np.flip(a)
print(reversed_arr)

[[3 6 1 8]
 [8 7 6 5]
 [4 3 2 1]]
